$.extend($.ui.raptor, Raptor, {

    // <expose>
    elementRemoveComments: elementRemoveComments,
    elementRemoveAttributes: elementRemoveAttributes,
    elementBringToTop: elementBringToTop,
    elementOuterHtml: elementOuterHtml,
    elementOuterText: elementOuterText,
    elementIsBlock: elementIsBlock,
    elementDefaultDisplay: elementDefaultDisplay,
    elementIsValid: elementIsValid,
    elementGetStyles: elementGetStyles,
    elementWrapInner: elementWrapInner,
    elementToggleStyle: elementToggleStyle,
    elementSwapStyles: elementSwapStyles,
    fragmentToHtml: fragmentToHtml,
    fragmentInsertBefore: fragmentInsertBefore,
    rangeExpandToParent: rangeExpandToParent,
    rangeGetCommonAncestor: rangeGetCommonAncestor,
    rangeIsEmpty: rangeIsEmpty,
    selectionSave: selectionSave,
    selectionRestore: selectionRestore,
    selectionDestroy: selectionDestroy,
    selectionEachRange: selectionEachRange,
    selectionReplace: selectionReplace,
    selectionSelectInner: selectionSelectInner,
    selectionSelectOuter: selectionSelectOuter,
    selectionSelectEdge: selectionSelectEdge,
    selectionSelectEnd: selectionSelectEnd,
    selectionSelectStart: selectionSelectStart,
    selectionGetHtml: selectionGetHtml,
    selectionGetElements: selectionGetElements,
    selectionToggleWrapper: selectionToggleWrapper,
    selectionExists: selectionExists,
    selectionReplaceSplittingSelectedElement: selectionReplaceSplittingSelectedElement,
    selectionReplaceWithinValidTags: selectionReplaceWithinValidTags,
    selectionToggleBlockStyle: selectionToggleBlockStyle,
    stringStripTags: stringStripTags,
    typeIsNumber: typeIsNumber,
    // </expose>

});
