builder.addModule({
    name: 'Text Style',
    type: 'plugin',
    files: [
        __dirname + '/block-quote.js',
        __dirname + '/bold.js',
        __dirname + '/italic.js',
        __dirname + '/size-decrease.js',
        __dirname + '/size-increase.js',
        __dirname + '/strike.js',
        __dirname + '/sub.js',
        __dirname + '/super.js',
        __dirname + '/underline.js',
        __dirname + '/style/block-quote.scss',
        __dirname + '/style/bold-front-end.scss',
        __dirname + '/style/bold.scss',
        __dirname + '/style/italic-front-end.scss',
        __dirname + '/style/italic.scss',
        __dirname + '/style/strike-front-end.scss',
        __dirname + '/style/strike.scss',
        __dirname + '/style/sub.scss',
        __dirname + '/style/super.scss',
        __dirname + '/style/text-size.scss',
        __dirname + '/style/underline-front-end.scss',
        __dirname + '/style/underline.scss',
        __dirname + '/style/images/edit-bold.png',
        __dirname + '/style/images/edit-italic.png',
        __dirname + '/style/images/edit-quotation.png',
        __dirname + '/style/images/edit-size-down.png',
        __dirname + '/style/images/edit-size-up.png',
        __dirname + '/style/images/edit-strike.png',
        __dirname + '/style/images/edit-subscript.png',
        __dirname + '/style/images/edit-superscript.png',
        __dirname + '/style/images/edit-underline.png'
    ]
});